CREATE TABLE cat_genero
(
    id_genero   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_by  VARCHAR(255)                            NOT NULL,
    updated_by  VARCHAR(255),
    created_at  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at  TIMESTAMP WITHOUT TIME ZONE,
    trace       INTEGER,
    active      BOOLEAN,
    descripcion VARCHAR(255),
    codigo      VARCHAR(255),
    CONSTRAINT pk_cat_genero PRIMARY KEY (id_genero)
);