CREATE TABLE entidad_cliente_pfae_ext
(
    id_cliente_pfae_ext   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_by            VARCHAR(255)                            NOT NULL,
    updated_by            VARCHAR(255),
    created_at            TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at            TIMESTAMP WITHOUT TIME ZONE,
    trace                 INTEGER,
    active                BOOLEAN,
    fecha_nacimiento      date,
    telefono              VARCHAR(255),
    id_cliente            BIGINT,
    correo_electronico    VARCHAR(255),
    id_pais_nacimiento    INTEGER,
    id_nacionalidad       INTEGER,
    id_genero             BIGINT,
    nombre                VARCHAR(255),
    apellido_paterno      VARCHAR(255),
    apellido_materno      VARCHAR(255),
    id_ocupacion          BIGINT,
    domicilio             VARCHAR(255),
    id_entidad_federativa BIGINT,
    direccion             VARCHAR(255),
    rfc                   VARCHAR(255),
    curp                  VARCHAR(255),
    direccion_local       VARCHAR(255),
    direccion_extranjera  VARCHAR(255),
    CONSTRAINT pk_entidad_cliente_pfae_ext PRIMARY KEY (id_cliente_pfae_ext)
);

ALTER TABLE entidad_cliente_pfae_ext
    ADD CONSTRAINT FK_ENTIDAD_CLIENTE_PFAE_EXT_ON_ID_GENERO FOREIGN KEY (id_genero) REFERENCES cat_genero (id_genero);

ALTER TABLE entidad_cliente_pfae_ext
    ADD CONSTRAINT FK_ENTIDAD_CLIENTE_PFAE_EXT_ON_ID_OCUPACION FOREIGN KEY (id_ocupacion) REFERENCES cat_ocupacion (id_ocupacion);