CREATE TABLE persona_fisica_mex
(
    id_cliente_pfae_mex   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_by            VARCHAR(255)                            NOT NULL,
    updated_by            VARCHAR(255),
    created_at            TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at            TIMESTAMP WITHOUT TIME ZONE,
    trace                 INTEGER,
    active                BOOLEAN,
    fecha_nacimiento      date,
    telefono              VARCHAR(255),
    id_cliente            BIGINT,
    id_genero             BIGINT,
    id_ocupacion          BIGINT,
    id_pais               BIGINT,
    id_entidad_federativa BIGINT,
    nombre                VARCHAR(255),
    apellido_paterno      VARCHAR(255),
    apellido_materno      VARCHAR(255),
    codigo_postal         VARCHAR(255),
    colonia               VARCHAR(255),
    municipio             VARCHAR(255),
    ciudad                VARCHAR(255),
    calle                 VARCHAR(255),
    numero_exterior       VARCHAR(255),
    numero_interior       VARCHAR(255),
    curp                  VARCHAR(255),
    rfc                   VARCHAR(255),
    id_suburb             VARCHAR(255),
    CONSTRAINT pk_personafisicamex PRIMARY KEY (id_cliente_pfae_mex)
);

ALTER TABLE persona_fisica_mex
    ADD CONSTRAINT FK_PERSONAFISICAMEX_ON_ID_ENTIDAD_FEDERATIVA FOREIGN KEY (id_entidad_federativa) REFERENCES cat_entidad_federativa (id_entidad_federativa);

ALTER TABLE persona_fisica_mex
    ADD CONSTRAINT FK_PERSONAFISICAMEX_ON_ID_GENERO FOREIGN KEY (id_genero) REFERENCES cat_genero (id_genero);

ALTER TABLE persona_fisica_mex
    ADD CONSTRAINT FK_PERSONAFISICAMEX_ON_ID_OCUPACION FOREIGN KEY (id_ocupacion) REFERENCES cat_ocupacion (id_ocupacion);