CREATE TABLE cat_codigos_postales
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_by        VARCHAR(255)                            NOT NULL,
    updated_by        VARCHAR(255),
    created_at        TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at        TIMESTAMP WITHOUT TIME ZONE,
    trace             INTEGER,
    active            BOOLEAN,
    codigo_postal     BIGINT,
    colonia           VARCHAR(255),
    tipo_asentamiento VARCHAR(255),
    municipio         VARCHAR(255),
    estado            VARCHAR(255),
    ciudad            VARCHAR(255),
    zona              VARCHAR(255),
    CONSTRAINT pk_cat_codigos_postales PRIMARY KEY (id)
);