CREATE SEQUENCE IF NOT EXISTS password_reset_token_seq START WITH 1 INCREMENT BY 50;

CREATE TABLE client_entity
(
    client_id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_by       VARCHAR(255)                            NOT NULL,
    updated_by       VARCHAR(255),
    created_at       TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at       TIMESTAMP WITHOUT TIME ZONE,
    trace            INTEGER,
    active           BOOLEAN,
    name             VARCHAR(255),
    last_name_father VARCHAR(255),
    last_name_mother VARCHAR(255),
    email            VARCHAR(255),
    password         VARCHAR(255),
    username         VARCHAR(255),
    lock_time        TIMESTAMP WITHOUT TIME ZONE,
    failed_attempts  INTEGER,
    email_verified   BOOLEAN,
    CONSTRAINT pk_client_entity PRIMARY KEY (client_id)
);

CREATE TABLE client_session
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    client_id         BIGINT                                  NOT NULL,
    latitud           DECIMAL(10, 7),
    longitud          DECIMAL(10, 7),
    start_date        TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    end_date          TIMESTAMP WITHOUT TIME ZONE,
    device            VARCHAR(255),
    ip_address        VARCHAR(255),
    agent             VARCHAR(255),
    current_session   BOOLEAN                                 NOT NULL,
    expired_session   BOOLEAN                                 NOT NULL,
    revoked_session   BOOLEAN                                 NOT NULL,
    active            BOOLEAN                                 NOT NULL,
    observations      TEXT,
    extra_information JSONB,
    CONSTRAINT pk_client_session PRIMARY KEY (id)
);

CREATE TABLE email_verification
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_by         VARCHAR(255)                            NOT NULL,
    updated_by         VARCHAR(255),
    created_at         TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at         TIMESTAMP WITHOUT TIME ZONE,
    trace              INTEGER,
    active             BOOLEAN,
    client_id          BIGINT,
    verification_token VARCHAR(255),
    expiration_date    TIMESTAMP WITHOUT TIME ZONE,
    is_deleted         BOOLEAN,
    is_validated       BOOLEAN,
    is_canceled        BOOLEAN,
    CONSTRAINT pk_email_verification PRIMARY KEY (id)
);

CREATE TABLE password_reset_token
(
    id          BIGINT       NOT NULL,
    token       TEXT,
    expiry_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    status      VARCHAR(255) NOT NULL,
    client_id   BIGINT       NOT NULL,
    CONSTRAINT pk_passwordresettoken PRIMARY KEY (id)
);

ALTER TABLE client_entity
    ADD CONSTRAINT uc_client_entity_username UNIQUE (username);

ALTER TABLE client_session
    ADD CONSTRAINT FK_CLIENT_SESSION_ON_CLIENT FOREIGN KEY (client_id) REFERENCES client_entity (client_id);

ALTER TABLE password_reset_token
    ADD CONSTRAINT FK_PASSWORDRESETTOKEN_ON_CLIENT FOREIGN KEY (client_id) REFERENCES client_entity (client_id);