CREATE TABLE client_validations
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_by     VARCHAR(255)                            NOT NULL,
    updated_by     VARCHAR(255),
    created_at     TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at     TIMESTAMP WITHOUT TIME ZONE,
    trace          INTEGER,
    active         BOOLEAN,
    lista_69b      JSONB,
    rfc            JSONB,
    curp           JSONB,
    datos_fiscales JSONB,
    client_id      BIGINT,
    CONSTRAINT pk_client_validations PRIMARY KEY (id)
);

ALTER TABLE client_validations
    ADD CONSTRAINT uc_client_validations_client UNIQUE (client_id);

ALTER TABLE client_validations
    ADD CONSTRAINT FK_CLIENT_VALIDATIONS_ON_CLIENT FOREIGN KEY (client_id) REFERENCES client_entity (client_id);