CREATE SEQUENCE IF NOT EXISTS password_reset_token_seq START WITH 1 INCREMENT BY 50;

CREATE TABLE client_type
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_by  VARCHAR(255)                            NOT NULL,
    updated_by  VARCHAR(255),
    created_at  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at  TIMESTAMP WITHOUT TIME ZONE,
    trace       INTEGER,
    active      BOOLEAN,
    description VARCHAR(255),
    key         VARCHAR(255),
    CONSTRAINT pk_client_type PRIMARY KEY (id)
);

CREATE TABLE nationality
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_by  VARCHAR(255)                            NOT NULL,
    updated_by  VARCHAR(255),
    created_at  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at  TIMESTAMP WITHOUT TIME ZONE,
    trace       INTEGER,
    active      BOOLEAN,
    description VARCHAR(255),
    CONSTRAINT pk_nationality PRIMARY KEY (id)
);

CREATE TABLE validation_status
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_by  VARCHAR(255)                            NOT NULL,
    updated_by  VARCHAR(255),
    created_at  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at  TIMESTAMP WITHOUT TIME ZONE,
    trace       INTEGER,
    active      BOOLEAN,
    description VARCHAR(255),
    CONSTRAINT pk_validation_status PRIMARY KEY (id)
);
